### PR TITLE
Updated console logging

### PR DESCRIPTION
**Pull request by rviscomi**
This is a followup to #115, which introduced logging diagnostic info. These changes include:

- Using console groups for each metric log
  - Moving all instances of the extension prefix (`[Web Vitals Extension]`) to the top-level groups, ie out of table headers
  - Color-coding the metric value by threshold rating
- Individual logs within each group for high-level diagnostic info
  - the LCP element
  - a warning that the LCP was inflated when the tab was loaded in the background (parity with the popup)
  - attribution for each layout shift contributing to CLS as a simplified list of shifted elements and the shift score
  - FID and INP interaction targets and types
- Reverting the table-specific user setting
- Adding usage instructions to the README

image

### CODE REVIEW

**Review by tunetheweb — APPROVED** [review]
OK I like it. Thanks for cleaning up.

I wish there was a way of presenting the CLS data better (e.g. in table format) but think this is the best we can do, while maintaining grouping and ability to hover the element to highlight it.

**Comment by tunetheweb** [comment]
@mmocny we good to merge this, or are you in the middle of your updates so woulds rather hold off for a bit?

@gilbertococchi any comments on this?

**Comment by mmocny** [comment]
Oh damn, I didn't see this and had a very similar patch locally.  Let's land this one and I'll rebase.

**Comment by gilbertococchi** [comment]
This is amazing, +1 to the latest changes with Grouping, I agree that putting the prefix in the table was a workaround and I like the fact that it allowed to have the "Target" as clickable element as well. LGTM

**Pull request merged**
